### ISSUE TITLE
Autoload working ?

### ISSUE THREAD

**Issue by mickaelperrin** [WPBP/Widgets-Helper#2]
Hey,

Thanks for continuing the work on this great class.

Could you tell me how you use the autoloading with this project ?

I added the dependency in my project composer.json file (project wide) and include the autoload in the wp-settings.

However, when the file is (auto)loaded the class WP_Widget is not defined and so the class WPH_Widget is not registered. I need to manually require (and not require_once) the file in my functions.php.

Is it a bug or do you have a better way to handle this ?

Thanks,

**Comment by Mte90** [comment]
Very strage because https://github.com/WPBP/WordPress-Plugin-Boilerplate-Powered use that without issues.
There are this kind of problems as I can remember on unit tests.
As you can see the library check for `Wp-Widget` maybe it is a problem when you invoke your widgets.
In the boilerplate the widgets initialized only on `plugin_loaded`.
And thanks for the support :-D
